---
provisioner:
  name: chef_zero

platforms:
  - name: debian-8.4

suites:
  - name: installation
    run_list:
      - flannel_test::installation
  - name: service
    run_list:
      - flannel_test::service
  - name: docker_integration
    run_list:
      - flannel_test::docker
